version: '3.2'
services:
  rest-apiweb:
    build:
      context: ./rest-api
      dockerfile: Dockerfile
    image: rest-api
    container_name: rest-api
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://psqldbserver:5432/test
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: test
    networks:
      - net-test
    depends_on:
      - psqldbserver
#    restart: always

  psqldbserver:
    image: postgres:11.4-alpine
    container_name: psqldbserver
    ports:
      - 5432:5432
    networks:
      - net-test
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - psqldata:/var/lib/postgresql

volumes:
  psqldata:
networks:
  net-test:
    driver: bridge